version: "3.9" # version docker-compose syntax

services:
  app:
    build:
      context: . # build Dockerfile inside current directory
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # mapping local app directory to running container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=devpassword
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword

volumes:
  dev-db-data: